# Generated by Django 4.1.2 on 2022-10-18 02:21

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('생활형 숙박시설', 'Residence'), ('오피스텔', 'Officetel')], default='오피스텔', max_length=30)),
                ('num_room', models.SmallIntegerField(default=1)),
                ('size_room', models.SmallIntegerField(default=84)),
                ('floor', models.SmallIntegerField(default=1)),
                ('direction', models.CharField(choices=[('북향', 'North'), ('북동향', 'NorthEast'), ('동향', 'East'), ('남동향', 'SouthEast'), ('남향', 'South'), ('남서향', 'SouthWest'), ('서향', 'West'), ('북서향', 'NorthWest')], default='남향', max_length=30)),
                ('parking', models.SmallIntegerField(default=1)),
                ('size_floor', models.SmallIntegerField(default=0)),
                ('size_building', models.SmallIntegerField(default=0)),
                ('age', models.CharField(default='1년차', max_length=30)),
                ('url', models.URLField(null=True)),
                ('status', models.CharField(choices=[('소유주 모집중', 'Open'), ('모집 완료', 'Complete'), ('지분 매수 가능', 'Exchange')], default='소유주 모집중', max_length=30)),
                ('share_price', models.IntegerField()),
                ('share_members', models.SmallIntegerField(default=0)),
                ('vacation_first_title', models.TextField(default='')),
                ('vacation_first_text', models.TextField(default='')),
                ('vacation_second_title', models.TextField(default='')),
                ('vacation_second_text', models.TextField(default='')),
                ('vacation_third_title', models.TextField(default='')),
                ('vacation_third_text', models.TextField(default='')),
                ('investment_point_first', models.TextField(default='')),
                ('investment_point_second', models.TextField(default='')),
                ('investment_point_third', models.TextField(default='')),
                ('investment_point_fourth', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=items.models.get_image_filename, verbose_name='workImage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=items.models.get_image_filename, verbose_name='vacationImage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=items.models.get_image_filename, verbose_name='mainImage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=items.models.get_image_filename, verbose_name='investmentImage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=items.models.get_image_filename, verbose_name='infoImage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
