# Generated by Django 4.1.2 on 2022-10-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='map_key',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='map_timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
