# Generated by Django 4.1.2 on 2023-01-05 04:42

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_map_key_item_map_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=items.models.get_image_filename, verbose_name='mobileWorkImage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
