# Generated by Django 4.1.2 on 2023-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_mobileworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='question',
        ),
        migrations.AddField(
            model_name='item',
            name='memorandum',
            field=models.FileField(null=True, upload_to='memorandum/', verbose_name='Memorandum'),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='result',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
